### ISSUE TITLE
Add some information about variables used as subcategories.

### ISSUE THREAD

**Issue by zoton2** [speedruncom/api#30]
As of just over 4 months ago now, [variables for a game can be used as subcategories](http://www.speedrun.com/The_Site/thread/lac6h), but the API itself doesn't expose any information yet on if a variable is used for a subcategory or not.

The most basic thing that could be done is adding a boolean to the [variables](https://github.com/speedruncom/api/blob/master/version1/variables.md) endpoint/object, also maybe add a way so you can filter variables so only ones that are used as subcategories are returned?

You can already filter the [leaderboards](https://github.com/speedruncom/api/blob/master/version1/leaderboards.md) endpoint by a variable so being able to return the correct leaderboard information based on a subcategory is already available, just no way of knowing what variables are actually subcategories.

**Comment by YaLTeR** [comment]
Perhaps subcategories need to behave a little more like actual categories, because for example if you want to get WR runs for a category you really want to get the WR run for each subcategory.

**Comment by sgt-kabukiman** [comment]
We have just updated the API and included a flag on variables as well as the additional details about values (rules and the misc flag).

We thought about presenting subcategory variables as categories, but ultimately decided against it:

For defining a leaderboard, a regular category is still needed, so subcategory variables do not stand on their own. Having them as categories in the API would suggest that "instead of any%, I can get the 150cc leaderboard!", when instead you still need to fetch the any% leaderboard.

Also, subcategory variables can apply to multiple categories, so we cannot even "fake it" (e.g. by interpreting the category ID in ``/leaderboards/$categoryID/...`` as a variable ID, because it leaves the question of any% vs. 100% open.

**Comment by YaLTeR** [comment]
When I request world record runs for a game via an API call like:
[https://www.speedrun.com/api/v1/games/n268nk6p/records?top=1&scope=full-game&empty=1](https://www.speedrun.com/api/v1/games/n268nk6p/records?top=1&scope=full-game&empty=1)
I get one run per category, ignoring subcategories. I think it makes more sense to get one run per category per subcategory.
