### ISSUE TITLE
User links are in a list

### ISSUE THREAD

**Issue by Dutchj** [speedruncom/api#5]
When getting user information, the links to their various accounts are in a list of objects with a "rel" and a "uri" property. I'm not sure if there are any internal reasons for this, but it would be easier to retrieve a specific link if links were an object with properties, where the property names are the rel names (twitter, youtube, hitbox etc.) and the values are the URIs.

**Comment by sgt-kabukiman** [comment]
This structure has been chosen on purpose, because we sometimes have multiple links with the same relation (multiple ``player`` links for a run, for example). This approach also leaves us room for adding more metadata to links, like a title or a hint on whether the link requires authentication.

I can see how accessing the twitch link of a user via ``user.links.twitch`` would be suuuper convenient, but easy extendibility is more important than avoid a few lines of code in API clients.
