### ISSUE TITLE
Getting a run by its web ID

### ISSUE THREAD

**Issue by emerick42** [speedruncom/api#9]
Is there any way of getting a run details using the ID of web URLs `http://www.speedrun.com/run/68828` ?

If these two types of IDs can have the same value, at least we should have a way to query a run by this `web_id`.

**Comment by CryZe** [comment]
The website should just switch to the obscured string based IDs as well. The way it currently works you constantly have issues with having the wrong type of ID.

**Comment by emerick42** [comment]
Yep, I agree. But this could be bothering for any guy having favorited/stored a run's link to just lose it. Keeping the old one is not disturbing as long as we can retrieve the API identiffier with it.

**Comment by sgt-kabukiman** [comment]
The website will switch to using the encoded ID in the very near future. In addition to that, I will probably add a link from the run page to the resource in the API as well (not sure yet if that's going to be a visible link (``<a>`´) or some meta information in the document head).

Old URLs will continue to work on a best-effort basis. I think there won't be that many, if any, conflicts, so we will match old URLs as before and just redirect to the new ones.

I would advise against performing custom string matching magic on the run URL (sr.com/run/8aufhigr) to extract the ID, and instead fetching the page and looking for that link. We might change the URL structure at any point and you do not want this kind of implicit dependency in your code. Encoding the ID in the run pages is primarily done for consistency reasons, not because we want to encourage people to do string magic on it.

I can see how a simple ``url.split('/')[-1]`` is a really convenient way to get the run ID, but understand that your code can fail suddenly at any time if you do that. :-)

(I'm not so concerned about manually constructing the API url after getting the run ID, because those URLs are well-defined and you may rely on them.)

**Comment by sgt-kabukiman** [comment]
Run IDs are now encoded on the website as well. Each run as a link to its representation in the API as well. Same goes for the games (see the sidebar).
